---
---
stages:
  - site-publish

# build a new version of the demo site
pages:
  stage: site-publish
  image: node:latest
  variables:
    VITE_BASE: "/"
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - cp -r dist public

  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
